datavisyn/visyn_scripts

bin/commands/generator/workspace/index.js
config/webpack.config.js

**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds support for prefixes in package.json, like @datavisyn/tdp_core. This is required for example when the workspace folder names differ from the package.json names (which is the case when using @datavisyn prefixes). 
-  

Added prefix support for package names

---

config/tsconfig.template.json
config/webpack.config.js

Closes #11 
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Added ability to override resolve aliases via .yo-rc-workspace.json.
-  

Added custom resolve aliases

---

bin/commands/lint.js

**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds `cypress` to the `eslint` command, to lint it as `src` and `tests` is linted. 
- Minor release as it only highlights any linting errors and will not cause any products to be not built.
-  

Add cypress folder to eslint config

---

config/webpack.config.js

Closes *list issues numbers here*
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- When in workspace mode `yarn start` crashes since there is no tsconfig
-  

Check if it is a workspace when reading tsconfig

---

config/storybook.main.template.js
package.json

* feat: add storybook main template (https://github.com/datavisyn/visyn_scripts/pull/49)

Release 7.0.0

---

.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/release.yml

Use correct workflow branches

---

.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/release.yml
package.json

* Use correct workflow branches (https://github.com/datavisyn/visyn_scripts/pull/52)

Release 7.0.1

---

config/storybook.main.template.js
package.json

* Mantine 7 (https://github.com/datavisyn/visyn_scripts/pull/54)

Release 7.0.2

---

config/rspack.config.js

**Issue**
**UI/UX/Vis**
**Code**
**PR**
- The compress function has some bugs (w/ arquero for example). See comment in PR for details.
-  

fix: disable compress in swc minify

---

config/rspack.config.js
package.json

* fix: disable compress in swc minify (https://github.com/datavisyn/visyn_scripts/pull/59)

Release 8.0.1

---

config/rspack.config.js
package.json

* fix: disable mangle as it creates build errors (https://github.com/datavisyn/visyn_scripts/pull/71)

Release 8.0.4

---

config/rspack.config.js

**Issue**
**UI/UX/Vis**
**Code**
**PR**
- allow completely disabling the devtool setting
-  

feat: allow disabling devtool

---

config/rspack.config.js

Proxy for security routes not needed any more as we moved these to `/api/....`
see: https://github.com/datavisyn/visyn_core/pull/257
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- 
-  

Refactor: remove security routes proxy

---

config/rspack.config.js
package.json

* feat: allow disabling devtool (https://github.com/datavisyn/visyn_scripts/pull/73)
* Refactor: remove security routes proxy (https://github.com/datavisyn/visyn_scripts/pull/67)

Release 9.0.0

---

config/rspack.config.js

**Issue**
**UI/UX/Vis**
**Code**
**PR**
- If there is a lenient tsconfig available, prefer that for the rspack checker process
-  

feat: prefer lenient config in ts checker

---

config/rspack.config.js

**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Disable CSS minimizer as has some bugs, i.e. a production build will show weird icon sizes in mantine-react-table.
-  

feat: disable LightningCssMinimizerRspackPlugin

---

config/eslintrc.template.js
package.json
tests_fixtures/standalone_template/.eslintrc.js
tests_fixtures/standalone_template/src/app/MainApp.stories.tsx
tests_fixtures/standalone_template/src/index.initialize.tsx
tests_fixtures/standalone_template/yarn.lock

**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds determistic import order eslint rule: https://medium.com/weekly-webtips/how-to-sort-imports-like-a-pro-in-typescript-4ee8afd7258a
- Non-breaking as it needs to be enabled in the `.eslintrc.js` via `optimizeImports: true`:
```js
module.exports = require('visyn_scripts/config/eslintrc.template')({ tsconfigRootDir: __dirname, optimizeImports: true });
```
To help us trigger the ESLint auto-fix feature, to resolve a lot of fixable ESLint issues that come from your current working file.
Create new VSCode settings.json file under ./vscode/settings.json
```json
{
"editor.formatOnSave": false,
"eslint.validate": [
"typescript"
],
"editor.codeActionsOnSave": {
"source.fixAll": true
}
}
```
-  

 feat: add ESLint rule for deterministic import order

---

tests_fixtures/standalone_template/package.json
tests_fixtures/standalone_template/yarn.lock

**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Updates standalone template to Storybook 8.5
-  

deps: upgrade template to storybook 8.5

---

config/rspack.config.js

**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Fix HMR by forcing single runtime chunk
-  

fix: add runtimeChunk single to fix HMR

---

package.json

Closes *list issues numbers here*
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Fixes some sass-embedded hoisting issues as a new version was released.
-  

deps: upgrade sass-embedded to ~1.85.0

---

config/rspack.config.js

**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds the __APP_NAME__ and __APP_DISPLAY_NAME__ properties as env variables from the package.json
-  

feat: add __APP_NAME__ and __APP_DISPLAY_NAME__

---

config/eslintrc.template.js

feat: Added useEffect rule for ESLint

---

config/tsconfig.lenient.template.json
config/tsconfig.template.json

**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Updates TS target to ES2024 for more modern transpiliation target and language features.
-  

feat: bump TS target to ES2024
